### ISSUE TITLE
[Stretch] DAG: Multiple inputs and outputs 

### ISSUE THREAD

**Issue by kthakore** [hotg-ai/rune#112] opened 2021-04-20 14:43 UTC
- [] Syntax for the Runefile  `--out`

**Comment by kthakore** [comment] 2021-04-27 14:58
@Ge-te  needs a few more variables in outputs. He has to follow up

**Comment by Michael-F-Bryan** [comment] 2021-05-18 08:59
Duplicate of #68.

**Closed by Michael-F-Bryan** 2021-05-18 08:59 UTC
