### ISSUE TITLE
Build fails for Rune v0.7.0 on Mac Big Sur

### ISSUE THREAD

**Issue by f0rodo** [hotg-ai/rune#308] opened 2021-09-18 17:14 UTC
`cargo build` on master  fails with 

```   Compiling env_logger v0.8.4
   Compiling tempfile v3.2.0
error: failed to run custom build command for `wasm3-sys v0.1.2`

Caused by:
  process didn't exit successfully: `/Users/kartikthakore/Documents/Hammer/Rune/rune/target/debug/build/wasm3-sys-e6b1b74c65417786/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Unable to generate bindings: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /Users/kartikthakore/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm3-sys-0.1.2/build.rs:78:35
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...```

**Comment by Michael-F-Bryan** [comment] 2021-09-18 19:39
Duplicate of #283 and #293.

You need to `cargo install bindgen` if you want to install `rune` from source. See [the docs](https://hotg.dev/docs/#install-from-source) for the full list of build dependencies.

**Closed by Michael-F-Bryan** 2021-09-18 19:39 UTC
