### ISSUE TITLE
Make Runes Work With Multiple Outputs

### ISSUE THREAD

**Issue by Mi1ind** [hotg-ai/rune#154] opened 2021-05-14 21:42 UTC
Currently Runes only work with models which have a single output.

For example: The [YAMNet model](https://github.com/hotg-ai/test-runes/tree/master/yamnet) has 3 separate outputs, as seen by `rune model-info`.

```console
$ rune model-info yamnet.tflite

Ops: 114
Inputs:
        waveform: Float32[1]
Outputs:
        Identity: Float32[1, 521]
        Identity_1: Float32[1, 1024]
        Identity_2: Float32[1, 64]
```
Running the Rune fails at Runtime:

```console
$ rune run yamnet.rune --capability=sound:assets/exercise_bike.wav

[2021-05-14T21:19:18.504Z INFO  rune::run] Running rune: yamnet.rune
[2021-05-14T21:19:19.641Z DEBUG rune_wasmer_runtime] Loading image
[2021-05-14T21:19:19.644Z DEBUG rune_wasmer_runtime] Instantiating the WebAssembly module
[2021-05-14T21:19:19.711Z DEBUG rune_wasmer_runtime] Loaded the Rune
[2021-05-14T21:19:19.711Z DEBUG rune_wasmer_runtime] Running the rune
Error: Call failed

Caused by:
    0: Unable to call the _call function
    1: RuntimeError: Unable to execute the model
    2: Unable to execute the model
    3: We can't handle models with less/more than 1 output
```

**Comment by Michael-F-Bryan** [comment] 2021-05-17 17:37
I believe this is a duplicate of #112. @Mi1ind, do you mind if I close it?

**Comment by Mi1ind** [comment] 2021-05-17 18:02
@Michael-F-Bryan, Sure, go ahead.

**Closed** 2021-05-18 04:18 UTC
Labels: area - runtime, category - enhancement
